blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    #path('', views.post_list, name='post_list'),
    #path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView, name='post_list_by_tag'),
    #path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('post/<int:pk>-<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>-<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>-<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('api/', include('blog.api.urls', namespace='api')),
    path('api/', include('reference.api.urls', namespace='api_reference')),
    path('api_auth/', include('rest_framework.urls')),
    path('reference/', include('reference.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reference/api/urls.py
from django.urls import path
from . import views

app_name='reference'
urlpatterns = [
    path('reference/', views.ReferenceListView.as_view(), name = 'api_reference_list'),
    path('reference/<int:pk>/', views.ReferenceDetailView.as_view(), name= 'api_reference_detail'),

]

reference/urls.py
from django.urls import path
from . import views

app_name = 'reference'
urlpatterns = [
    #path('', views.post_list, name='post_list'),
    #path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.ReferenceListView.as_view(), name='reference_list'),
    #path('', views.PostListView.as_view(('reference.urls', 'post_list'), namespace='post_list')),
    #path('tag/<slug:tag_slug>/', views.PostListView, name='post_list_by_tag'),
    #path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    #path('post/<int:pk>-<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    #path('<int:post_id>/share/', views.post_share, name='post_share'),
    #path('feed/', LatestPostsFeed(), name='post_feed'),
    #path('search/', views.post_search, name='post_search'),
    path('reference/add/', views.ReferenceCreateView.as_view(), name='reference_create'),
    path('reference/<int:pk>-<slug:slug>/update/', views.ReferenceUpdateView.as_view(), name='reference_update'),
    path('reference/<int:pk>-<slug:slug>/delete/', views.ReferenceDeleteView.as_view(), name='reference_delete'),
    
]

reference/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your models here.
class GetReferenceManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()

class Reference(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish', blank=True)
    description = models.TextField()
    link = models.URLField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #on_delete=models.CASCADE, related_name = 'blog_posts')created = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)

    objects = models.Manager()
    getReference = GetReferenceManager()

    class Meta:
        #ordering = ('created',)
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('reference:reference_list')

reference/api/views.py
from rest_framework import generics, mixins, permissions
from ..models import Reference
from .serializers import ReferenceSerializer
from .permissions import IsAuthorOrReadOnly
from django.utils.text import slugify

class ReferenceListView(generics.ListCreateAPIView):
    queryset = Reference.getReference.all()
    serializer_class = ReferenceSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        if serializer.is_valid():
            serializer.save(author = self.request.user, slug=slugify(serializer.validated_data['title'], allow_unicode=True))

class ReferenceDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Reference.getReference.all()
    serializer_class = ReferenceSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]

    def perform_update(self, serializer):
        if serializer.is_valid():
            serializer.save(slug=slugify(serializer.validated_data['title'], allow_unicode=True))

reference/views.py
from django.shortcuts import render, get_object_or_404
from .models import Reference
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.text import slugify

# Create your views here.
@login_required
def reference_list(request, tag_slug=None):

    object_list = Reference.published.all()

    paginator = Paginator(object_list, 2)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'reference/post/list.html', {'posts': posts, 'page': page})

class ReferenceListView(LoginRequiredMixin, ListView):
    #sebenernya postlistview udah tampil, tp butuh overide biar gk cuma listnya aja yg tampil
    queryset = Reference.objects.all() #atribut list view, data view apa
    context_object_name = 'posts' #dari nama template list makanya posts
    paginate_by = 2
    template_name = 'reference/post/list.html'
    #overide superclass si tag_slug
    def get_queryset(self):
        qs = super().get_queryset()
        tag_slug = self.kwargs.get('tag_slug') #ambil dari urls/py body

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            qs = qs.filter(tags__in =[tag])
            self.tag = tag #self pointer ke instance
        else:
            self.tag = None #variabel ada saat sign suatu value

        return qs

    def get_context_data(self, **kwargs): #** kwargs argument bentuk dictionary merujuk line 35 posts
        context = super().get_context_data(**kwargs)

        if self.tag:
            context['tag'] = self.tag

        return context

class ReferenceCreateView(LoginRequiredMixin, CreateView):
    model = Reference
    fields =['title', 'description', 'link']
    template_name = 'reference/post/reference_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        #form.instance.status = 'published'
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)
        #ambil form instance, balikin ke super form_valid krn di super ada form save, jd datanya udah ditambah
        return super().form_valid(form)

class ReferenceUpdateView(LoginRequiredMixin, UpdateView):
    model = Reference
    fields = ['title', 'description', 'link']
    template_name = 'reference/post/reference_form.html'
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()

        return qs.filter(author = self.request.user)

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)

        return super().form_valid(form)

class ReferenceDeleteView(LoginRequiredMixin, DeleteView):
    model = Reference
    template_name = 'reference/post/reference_confirm_delete.html'
    success_url = reverse_lazy('reference:reference_list')
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

reference/templates/reference/post/latest_reference.html
<ul>
    {% for reference in latest_reference %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ reference.title }}
            </a>
        </li>
    {% endfor %}
</ul>

reference/templates/reference/post/list.html
{% extends 'blog/base.html' %}
{% load reference_tags %}

{% block title %}
    My Reference
{% endblock title %}


{% block content %}
    <h1>Reference</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for reference in posts %}
        <h2>
            <a href="#">
                {{ reference.title }}
            </a>
        </h2>
        
        
        <p class="date">
            Created {{ reference.created }} by {{ reference.author }}
        </p>
        {{ reference.description|markdown|truncatewords_html:30 }}
        
        <p>
            <a href="{{ reference.link }}">{{ reference.link }}</a>
        </p>
        
        {% if reference.author == request.user %}
        <p>
            <a href="{% url 'reference:reference_update' reference.id reference.slug %}">Update Reference</a> |
            <a href="{% url 'reference:reference_delete' reference.id reference.slug %}">Delete Reference</a>
        </p>
        {% endif %}
    {% endfor %}

    {% include "pagination.html" with page=page_obj %}
{% endblock content%}

reference/templates/reference/post/reference_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}Delete Reference{% endblock title %}

{% block content %}
    <h1>Delete Reference</h1>
    <form action="" method="post">
        <p>Are you sure want to delete this item <strong>{{object}}</strong>?</p>
        {% csrf_token  %}
        <p><input type="submit" value="Confirm"></p>
    </form>
{% endblock content %}

reference/templates/reference/post/reference_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create/Update References
{% endblock title %}

{% block content %}
    <h1>
        {% if 'add' in request.path|slice:'-4:' %}<!--add di path 4 terakhir liat urls.py-->
            Create Reference
        {% else %}
            Update Reference
        {% endif %}
    </h1>
    <form action="" method="post">
        {% for field in form %}
            <div class="row">
                <div class="col">
                    {{ field|as_crispy_field }} <!--hasilnya satu html-->
                </div>
            </div>
        {% endfor %}
        
        {% csrf_token %}
        <br><br>
        <p><input type="submit" 
            value="{% if 'add' in request.path|slice:'-4:' %}
                        Create 
                    {% else %}
                        Update 
                    {% endif %}">
            <!--class='btn btn-primary'>-->
        </p>
    </form>
{% endblock content%}